name: Auto deploy to AWS lambda function

on:
  push:
    branches:
      - "deploy"
  pull_request:
    branches:
      - "master"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: Push tagged image to AWS ECR repository
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      username: ${{ steps.login-ecr.outputs.docker_username_public_ecr_aws }}
      password: ${{ steps.login-ecr.outputs.docker_password_public_ecr_aws }}

  deploy:
    runs-on: ubuntu-latest
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload Lambda function from ECR image
        run: |
          aws lambda get-function --function-name ${{ secrets.AWS_LAMBDA_FUNCTION }}
          if [ $? -eq 0 ]
          then
            aws lambda update-function-code \
              --publish --function-name ${{ secrets.AWS_LAMBDA_FUNCTION }} \
              --image-uri ${{ needs.image.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}
          else
            aws lambda create-function \
              --timeout 900 --package-type Image \
              --function-name ${{ secrets.AWS_LAMBDA_FUNCTION }} --role=${{ secrets.AWS_ROLE_ARN }} \
              --code ImageUri=${{ needs.image.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }} \
              --environment Variables={AWS_SOURCE_BUCKET=${{ secrets.AWS_SOURCE_BUCKET }},AWS_DESTINATION_BUCKET=${{ secrets.AWS_DESTINATION_BUCKET}}}
          fi
