name: Invoke AWS lambda function periodically

on:
  schedule:
    - '0 0 * * *' # Runs every day at midnight UTC

jobs:
  trigger:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws lambda invoke --function-name ${{ secrets.AWS_LAMBDA_FUNCTION }} /tmp/${{ secrets.AWS_LAMBDA_FUNCTION }}.txt
